# Generated by Django 4.0.5 on 2022-06-10 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_short_url_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 7, 41, 22, 113664, tzinfo=utc)),
        ),
    ]
