# Generated by Django 4.0.5 on 2022-06-10 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_alter_short_url_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_url',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 7, 48, 46, 895635, tzinfo=utc)),
        ),
    ]
