# Generated by Django 4.0.5 on 2022-06-10 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_alter_short_url_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_url',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='short_url',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 11, 41, 36, 684197)),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 11, 41, 36, 684178)),
        ),
    ]
