# Generated by Django 4.0.5 on 2022-06-10 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0006_remove_short_url_is_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 11, 49, 20, 562996)),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 11, 49, 20, 563013)),
        ),
    ]
