# Generated by Django 4.0.5 on 2022-06-10 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0007_alter_short_url_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 12, 57, 56, 634562)),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 12, 57, 56, 634582)),
        ),
    ]
