# Generated by Django 4.0.5 on 2022-06-10 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0008_alter_short_url_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_url',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 12, 58, 26, 454953)),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 12, 58, 26, 454971)),
        ),
    ]
